[package]
name = "launchkey-sdk"
version = "0.1.4"
authors = ["Borna Cvitanić borna.cvitanic@gmail.com"]
description = "A type-safe Rust SDK for Novation Launchkey MIDI controllers. Enables full control over pads, encoders, faders, displays, and DAW integration with support for RGB colors, bitmaps, and cross-platform development."
repository = "https://github.com/bornacvitanic/launchkey-sdk"
license-file = "../LICENSE.md"
readme = "../README.md"
edition = "2021"
keywords = ["midi", "launchkey", "novation", "controller", "sdk"]
categories = ["hardware-support", "api-bindings", "multimedia::audio", "development-tools"]

[lib]
path  = "src/lib.rs"

[dependencies]
midir = "0.10.1"
wmidi = "4.0.10"
strum = "0.27.1"
strum_macros = "0.27.1"
image = "0.25.5"
thiserror = "2.0.12"